calculator/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('calculator/', views.calculator_view, name='calculator'),
    path('import/', views.importar_xlsx, name='importar_xlsx'),
    path('consumers/', views.consumer_list, name='consumer_list'),
    path('add_consumer/', views.add_consumer, name='add_consumer')

]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('calculator.urls')),
]

calculator/models.py
from django.db import models

class ConsumerTypes(models.TextChoices):
    RESIDENCIAL = 'Residencial'
    COMERCIAL = 'Comercial'
    INDUSTRIAL = 'Industrial'


class Consumer(models.Model):
    name = models.CharField("Nome do Consumidor", max_length=128)
    document = models.CharField("Documento(CPF/CNPJ)", max_length=14, unique=True)
    zip_code = models.CharField("CEP", max_length=8, null=True, blank=True)
    city = models.CharField("Cidade", max_length=128)
    state = models.CharField("Estado", max_length=128)
    consumption = models.IntegerField("Consumo(kWh)", blank=True, null=True)
    distributor_tax = models.FloatField("Tarifa da Distribuidora", blank=True, null=True)
    discount_rule = models.ForeignKey('DiscountRule', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name


class DiscountRule(models.Model):
    consumption_range = models.CharField("Faixa de Consumo", max_length=50)
    consumer_type = models.CharField("Tipo de Consumidor", max_length=50, choices=ConsumerTypes.choices)
    cover_value = models.FloatField("Valor de Cobertura")
    discount_value = models.FloatField("Valor do Desconto")

    def __str__(self):
        return f"{self.consumer_type} - {self.consumption_range}"

calculator/forms.py
from django import forms
from .models import Consumer, ConsumerTypes
from .validation import validate_cpf, validate_cnpj


class ConsumptionForm(forms.Form):
    consumption_month1 = forms.FloatField(label='Consumo do Mês 1')
    consumption_month2 = forms.FloatField(label='Consumo do Mês 2')
    consumption_month3 = forms.FloatField(label='Consumo do Mês 3')
    distributor_tax = forms.FloatField(label='Distributor Tax')
    tax_type = forms.ChoiceField(label="Tipo de Consumidor", choices=ConsumerTypes.choices)


class ConsumerForm(forms.ModelForm):
    class Meta:
        model = Consumer
        fields = ['name', 'document', 'zip_code', 'city', 'state', 'consumption', 'distributor_tax',]

    def clean_document(self):
        document_type = self.cleaned_data.get('document_type')
        document = self.cleaned_data.get('document')

        if document_type == 'CPF':
            if not validate_cpf(document):
                raise forms.ValidationError('CPF inválido ou já cadastrado.')
        elif document_type == 'CNPJ':
            if not validate_cnpj(document):
                raise forms.ValidationError('CNPJ inválido ou já cadastrado.')

        return document

    def clean(self):
        cleaned_data = super().clean()
        document = cleaned_data.get('document')

        if Consumer.objects.filter(document=document).exists():
            raise forms.ValidationError('Este documento já está cadastrado.')

        return cleaned_data

calculator/views.py
from django.shortcuts import render, redirect
from .forms import ConsumptionForm, ConsumerForm
from calculator_python import calculator
import pandas as pd
from .models import Consumer, DiscountRule, ConsumerTypes
from django.contrib import messages




def index(request):
    return render(request, 'index.html')

def calculator_view(request):
    if request.method == 'POST':
        form = ConsumptionForm(request.POST)
        if form.is_valid():
            consumption = [
                form.cleaned_data['consumption_month1'],
                form.cleaned_data['consumption_month2'],
                form.cleaned_data['consumption_month3']
            ]
            distributor_tax = form.cleaned_data['distributor_tax']
            tax_type = form.cleaned_data['tax_type']
            result = calculator(consumption, distributor_tax, tax_type)
            context = {'result': result}
            return render(request, 'result.html', context)
    else:
        form = ConsumptionForm()
    return render(request, 'form.html', {'form': form})


def importar_xlsx(request):
    if request.method == 'POST':
        if 'file' in request.FILES:
            file = request.FILES['file']
            if file.name.endswith('.xlsx'):
                df = pd.read_excel(file)
                
                for index, row in df.iterrows():
                    consumer, created = Consumer.objects.get_or_create(
                        document=row['Documento'],
                        defaults={
                            'name': row['Nome'],
                            'zip_code': row['Cidade'],  
                            'city': row['Cidade'],       
                            'state': row['Estado'],
                            'consumption': row['Consumo(kWh)'],
                            'distributor_tax': row['Tarifa da Distribuidora']
                        }
                    )

                    discount_rule, created = DiscountRule.objects.get_or_create(
                        consumption_range=row['Consumo(kWh)'],
                        consumer_type=row['Tipo'],              
                        defaults={
                            'cover_value': row['Cobertura(%)'],  
                            'discount_value': row['Cobertura(%)']
                        }
                    )

                    consumer.discount_rule = discount_rule
                    consumer.save()
                
                return redirect('index')  
            else:
                return render(request, 'import_error.html', {'error_message': 'O arquivo enviado não é um arquivo Excel (.xlsx).'})
        else:
            return render(request, 'import_error.html', {'error_message': 'Nenhum arquivo enviado.'})
    else:
        return render(request, 'import_form.html')


def consumer_list(request):
    consumers = Consumer.objects.all().select_related('discount_rule')

    consumer_type = request.GET.get('consumer_type')
    consumption_min = request.GET.get('consumption_min')
    consumption_max = request.GET.get('consumption_max')

    if consumer_type:
        consumers = consumers.filter(discount_rule__consumer_type=consumer_type)
    if consumption_min:
        consumers = consumers.filter(consumption__gte=consumption_min)
    if consumption_max:
        consumers = consumers.filter(consumption__lte=consumption_max)

    data = []
    for consumer in consumers:
        if consumer.discount_rule:
            monthly_savings = (
                consumer.consumption * consumer.distributor_tax *
                consumer.discount_rule.discount_value * consumer.discount_rule.cover_value
            )
            annual_savings = monthly_savings * 12
        else:
            monthly_savings = 0
            annual_savings = 0

        data.append({
            "consumer": consumer,
            "monthly_savings": round(monthly_savings, 2),
            "annual_savings": round(annual_savings, 2)
        })

    return render(request, 'list.html', {'consumers_data': data})

def add_consumer(request):
    discount_rule_choices = [(choice[0], choice[1]) for choice in ConsumerTypes.choices]
    if request.method == 'POST':
        form = ConsumerForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Consumidor adicionado com sucesso!')
            return redirect('consumer_list')
        else:
            print(form.errors)
            messages.error(request, 'O formulário contém erros. Por favor, corrija-os.')
    else:
        form = ConsumerForm()
    return render(request, 'add_consumer.html', {'form': form, 'discount_rule_choices': discount_rule_choices})


# TODO: Your list view should do the following tasks
"""
-> Recover all consumers from the database
-> Get the discount value for each consumer
-> Calculate the economy
-> Send the data to the template that will be rendered
"""


def view1(request):
    # Create the first view here.
    pass


# TODO: Your create view should do the following tasks
"""Create a view to perform inclusion of consumers. The view should do:
-> Receive a POST request with the data to register
-> If the data is valid (validate document), create and save a new Consumer object associated with the right discount rule object
-> Redirect to the template that list all consumers

Your view must be associated with an url and a template different from the first one. A link to
this page must be provided in the main page.
"""


def view2():
    # Create the second view here.
    pass

calculator/templates/add_consumer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adicionar Consumidor</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/add_consumer_style.css' %}">
    <script>
        function fetchAddress() {
            var cep = document.getElementById('zip_code').value;
            if (cep.length == 8) {
                var url = 'https://viacep.com.br/ws/' + cep + '/json/';
                fetch(url)
                    .then(response => response.json())
                    .then(data => {
                        if (!data.erro) {
                            document.getElementById('city').value = data.localidade;
                            document.getElementById('state').value = data.uf;
                        } else {
                            alert('CEP não encontrado.');
                        }
                    })
                    .catch(error => console.error('Erro ao buscar endereço:', error));
            } else {
                alert('CEP inválido.');
            }
        }
    </script>
</head>
<body>
    <h1>Adicionar Consumidor</h1>
    <form method="post" action="{% url 'add_consumer' %}">
        {% csrf_token %}
        {% if form.errors %}
        <div class="error-message">
            {% for field, errors in form.errors.items %}
                {% for error in errors %}
                    <p class="error">{{ field|capfirst }}: {{ error }}</p>
                {% endfor %}
            {% endfor %}
        </div>
        {% endif %}
        <label for="name">Nome do Consumidor:</label>
        <input type="text" id="name" name="name" required>
        
        <label for="document">Documento(CPF/CNPJ):</label>
        <input type="text" id="document" name="document" required>
        
        <label for="zip_code">CEP:</label>
        <input type="text" id="zip_code" name="zip_code" required onblur="fetchAddress()">
        
        <label for="city">Cidade:</label>
        <input type="text" id="city" name="city" required>
        
        <label for="state">Estado:</label>
        <input type="text" id="state" name="state" required>
        
        <label for="consumption">Consumo (kWh):</label>
        <input type="number" id="consumption" name="consumption" required>
        
        <label for="distributor_tax">Tarifa da Distribuidora:</label>
        <input type="number" id="distributor_tax" name="distributor_tax" required>
        
        <label for="discount_rule">Tipo:</label>
        <select id="discount_rule" name="discount_rule" class="custom-select" required>
            {% for choice in discount_rule_choices %}
                <option value="{{ choice.0 }}">{{ choice.1 }}</option>
            {% endfor %}
        </select>
        
        <label for="coverage">Cobertura(%):</label>
        <input type="number" id="coverage" name="coverage" required>
        
        <button type="submit">Adicionar Consumidor</button>
        
    </form>
    
    <a href="{% url 'consumer_list' %}" class="btn">Voltar para a Lista de Consumidores</a>
    <a href="{% url 'index' %}" class="btn">Voltar para o Início</a>

</body>
</html>

calculator/templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calculadora</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/form_style.css' %}">
</head>
<body>
    <header>
        <h1>Bem-vindo à calculadora!</h1>
    </header>
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_consumption_month1">Consumo do Mês 1:</label>
                {{ form.consumption_month1 }}
            </div>
            <div class="form-group">
                <label for="id_consumption_month2">Consumo do Mês 2:</label>
                {{ form.consumption_month2 }}
            </div>
            <div class="form-group">
                <label for="id_consumption_month3">Consumo do Mês 3:</label>
                {{ form.consumption_month3 }}
            </div>
            <div class="form-group">
                <label for="id_distributor_tax">Distributor Tax:</label>
                {{ form.distributor_tax }}
            </div>
            <div class="form-group">
                <label for="id_tax_type">Tax Type:</label>
                {{ form.tax_type }}
            </div>
            <button type="submit">Calcular</button>
        </form>
        <a href="{% url 'index' %}" class="btn-voltar">Voltar para o Inicio</a>
    </div>
</body>
</html>

calculator/templates/import_form.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Importar Arquivo Excel</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/import_form_style.css' %}">

</head>
<body>
    <div class="container">
        <h2>Importar Arquivo Excel</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="file" class="custom-file-upload">
                Selecione um arquivo Excel
                <input type="file" name="file" id="file">
            </label>
            <br><br>
            <input type="submit" value="Importar" class="custom-file-upload">
            <a href="{% url 'index' %}" class="btn-voltar">Voltar para o Inicio</a>

        </form>
    </div>
</body>
</html>

calculator/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Minha Página Inicial</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/index_style.css' %}">
</head>
<body>
    <header>
        <h1>Bem-vindo à minha aplicação!</h1>
    </header>
    <div class="container">
        <ul>
            <li>
                <a class="icon-link" href="{% url 'calculator' %}">
                    <img src="{% static 'img/calculadora.png' %}" alt="Ícone da Calculadora">
                    <span>Calculadora</span>
                </a>
            </li>
            <li>
                <a class="icon-link" href="{% url 'importar_xlsx' %}">
                    <img src="{% static 'img/importar.png' %}" alt="Ícone de Importação de Dados">
                    <span>Importar Dados</span>
                </a>
            </li>
            <li>
                <a class="icon-link" href="{% url 'consumer_list' %}">
                    <img src="{% static 'img/consumo-de-energia.png' %}" alt="Ícone de lista de Consumidores">
                    <span>Consumidores</span>
                </a>
            </li>
        </ul>
    </div>
</body>
</html>

calculator/templates/list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/list_style.css' %}">
    <title>Lista de Consumidores</title>
</head>
<body>
    <h1>Lista de Consumidores</h1>

    <form method="get" action="{% url 'consumer_list' %}">
        <label for="consumer_type">Filtrar por Tipo:</label>
        <select id="consumer_type" name="consumer_type">
            <option value="">Todos</option>
            <option value="Residencial">Residencial</option>
            <option value="Comercial">Comercial</option>
            <option value="Industrial">Industrial</option>
        </select>
    
        <label for="consumption_min">Consumo Mínimo:</label>
        <input type="number" id="consumption_min" name="consumption_min">
    
        <label for="consumption_max">Consumo Máximo:</label>
        <input type="number" id="consumption_max" name="consumption_max">
    
        <button type="submit">Filtrar</button>
    </form>

    <table>
        <thead>
            <tr>
                <th>Nome</th>
                <th>Documento</th>
                <th>CEP</th>
                <th>Cidade</th>
                <th>Estado</th>
                <th>Consumo (kWh)</th>
                <th>Tarifa da Distribuidora</th>
                <th>Regra de Desconto</th>
                <th>Economia</th>
            </tr>
        </thead>
        <tbody>
            {% for consumer_data in consumers_data %}
            <tr>
                <td>{{ consumer_data.consumer.name }}</td>
                <td>{{ consumer_data.consumer.document }}</td>
                <td>{{ consumer_data.consumer.zip_code }}</td>
                <td>{{ consumer_data.consumer.city }}</td>
                <td>{{ consumer_data.consumer.state }}</td>
                <td>{{ consumer_data.consumer.consumption }}</td>
                <td>{{ consumer_data.consumer.distributor_tax }}</td>
                <td>{{ consumer_data.consumer.discount_rule }}</td>
                <td>{{ consumer_data.monthly_savings|floatformat:2 }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'index' %}" class="btn-voltar">Voltar para o Início</a>
    <a href="{% url 'add_consumer' %}" class="btn-adicionar">Adicionar Consumidor</a>

</body>
</html>

calculator/templates/result.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resultado</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/result_style.css' %}">
</head>
<body>
    <header>
        <h1>Resultado:</h1>
    </header>
    <div class="container">
        <p><strong>Economia Anual:</strong> R$ {{ result.0 }}</p>
        <p><strong>Economia Mensal:</strong> R$ {{ result.1 }}</p>
        <p><strong>Desconto Aplicado:</strong> {{ result.2 }}%</p>
        <p><strong>Cobertura:</strong> {{ result.3 }}</p>

        <a href="{% url 'index' %}" class="btn-voltar">Voltar para o Inicio</a>

    </div>
</body>
</html>